# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'


- script: |
   wget https://github.com/github/codeql-action/releases/latest/download/codeql-runner-linux
   chmod +x codeql-runner-linux
   
  displayName: 'Get latest CodeQL package. Install on Agent.'

- script: |
   ./codeql-runner-linux init \
   --repository sq2907/WebGoat.NET \
   --github-url https://github.com \
   --github-auth $(GitHub Token) \
  displayName: 'Initialize CodeQL Executable and create a CodeQL database' 

- script: |
    chmod +x ./codeql-runner/codeql-env.sh
    ./codeql-runner/codeql-env.sh \
    --repository sq2907/WebGoat.NET \
    --github-url https://github.com \
    --github-auth $(GitHub Token) \
  displayName: 'Run the Script' 


- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    clean: true
    restoreNugetPackages: true

- script: |
   ./codeql-runner-linux analyze \
   --repository sq2907/WebGoat.NET \
   --github-url https://github.com \
   --github-auth $(GitHub Token) \
   --commit $(Build.SourceVersion) \
   --ref $(Build.SourceBranch)
  displayName: 'Populate the CodeQL runner databases, analyze them, and upload the results to GitHub.'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'hello world' 
      
      echo 'javascript - codeql_database ls -l'
      
      ls -l /home/vsts/work/1/s/codeql-runner/codeql_databases
      
      echo 'javascript - codeql_database/javascript ls -l'
      
      ls -l /home/vsts/work/1/s/codeql-runner/codeql_databases/javascript
      
      
      echo 'csharp - codeql_database ls -l'
      
      ls -l /home/vsts/work/1/s/codeql-runner/codeql_databases
      
      echo 'csharp - codeql_database/csharp ls -l'
      
      ls -l /home/vsts/work/1/s/codeql-runner/codeql_databases/csharp
      
      
      echo 'csharp - codeql-runner-tools'
      
      ls -l /home/vsts/codeql-runner-tools/CodeQL/0.0.0-20210127/x64/codeql/codeql
      
      echo 'csharp - codeql-runner-tools - cat '
      
      cat /home/vsts/codeql-runner-tools/CodeQL/0.0.0-20210127/x64/codeql/codeql



